# Copyright 2026 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
no_package = True
skip_missing_interpreters = True
env_list = format, lint, unit
min_version = 4.0.0

[vars]
src_path = {tox_root}/src
tests_path = {tox_root}/tests
lib_path = {tox_root}/lib/charms/git_integrator
all_path = {[vars]src_path} {[vars]tests_path} {[vars]lib_path}
uv_flags = --isolated

[testenv]
allowlist_externals = uv
basepython = python3
set_env =
    PYTHONPATH = {tox_root}:{tox_root}/lib:{[vars]src_path}
    PYTHONBREAKPOINT=pdb.set_trace
    PY_COLORS=1
pass_env =
    PYTHONPATH
    CHARM_BUILD_DIR
    MODEL_SETTINGS

[testenv:lock]
description = Update uv.lock with the latest deps
commands =
  uv lock --upgrade --no-cache

[testenv:format]
description = Apply coding style standards to code
deps =
    .[format]
commands =
    uv tool run {[vars]uv_flags} ruff format {[vars]all_path}
    uv tool run {[vars]uv_flags} ruff check --fix {[vars]all_path}

[testenv:lint]
description = Check code against coding style standards, and static checks
deps =
    .[lint]
commands =
    uv sync --active --group lint
    uv tool run {[vars]uv_flags} codespell {tox_root}
    uv tool run {[vars]uv_flags} ruff check {[vars]all_path}

[testenv:unit]
description = Run unit tests
deps =
    .[unit]
allowlist_externals =
    {[testenv]allowlist_externals}
commands =
    uv sync --active --group unit
    uv run coverage run \
        --source={[vars]src_path} --source={[vars]lib_path} --module pytest \
        {[vars]tests_path}/unit \
        {posargs}
    uv tool run {[vars]uv_flags} coverage report
